import Head from 'next/head';
import { useState, useEffect } from 'react';
import CardContainer from 'colorz/components/CardContainer';

export default function Home() {
    const [firstColor, setFirstColor] = useState<string>('#FF00EA');
    const [secondColor, setSecondColor] = useState<string>('#FFC800');
    const [thirdColor, setThirdColor] = useState<string>('#3AFF00');
    const [fourthColor, setFourthColor] = useState<string>('#009CFF');
    //
    const [fC050, setFC050] = useState<string>('#FCDCFA');
    const [fC100, setFC100] = useState<string>('#F5B3EF');
    const [fC200, setFC200] = useState<string>('#E88BE0');
    const [fC300, setFC300] = useState<string>('#D667CD');
    const [fC400, setFC400] = useState<string>('#C246B7');
    const [fC500, setFC500] = useState<string>('#AB2CA0');
    const [fC600, setFC600] = useState<string>('#8F1885');
    const [fC700, setFC700] = useState<string>('#700C68');
    const [fC800, setFC800] = useState<string>('#4F0449');
    const [fC900, setFC900] = useState<string>('#2B0128');

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen w-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <CardContainer
                    firstColor={firstColor}
                    secondColor={secondColor}
                    thirdColor={thirdColor}
                    fourthColor={fourthColor}
                    firstColorScheme={{
                        fC050,
                        fC100,
                        fC200,
                        fC300,
                        fC400,
                        fC500,
                        fC600,
                        fC700,
                        fC800,
                        fC900,
                    }}
                />
            </main>
        </>
    );
}
